### ISSUE TITLE
Black spots on the map

### ISSUE THREAD

**Issue by Komoden** [webbukkit/DynmapForge#38] opened 2014-12-10 11:37 UTC
The map on the server that i'm hosting has an odd tendency for black spots.

Earlier today i flew around a rather large area doing radiusrenders... everything was fine, until i left the areas again, then small patches turned black again..

Is it a problem with renders triggering on chunks while they are unloading?

**Comment by mikeprimm** [comment] 2015-01-06 20:26
Definitely start by moving to either the release level Dynmap 2.0 (not the alpha), or to the latest 2.1 builds (either 2.1-alpha-1 or the dev build for 2.1-alpha-2).   2.0.0-alpha-2 dates back to August.

http://mikeprimm.com/dynmap/builds/DynmapForge/

**Comment by jmurrayufo** [comment] 2015-03-20 19:09
I can confirm same issues happening with Dynmap-HEAD-forge-1.7.10.jar (linked as the 2.2 alpha build) and Dynmap-2.1-forge-1.7.10.jar. 

Mine craft versions for me: minecraft_server.1.7.10, and FTBServer-1.7.10-1291. Specifically the Direwolf20 1.1.1 server. 

The Dynmap 2.1 version worked flawlessly with a tekkit 1.10c setup, but seems to have this "black chunks" issue on the new version. 

Things I have tried so far to fix the issue:
 * Lowering TPS thresholds
 * Making sure that the server doesn't pause/scale back updates with players on
 * Make sure with the /dynmap pause command shows Full, Update and Zoom to be ACTIVE. 
 * Reinstall of both versions of the mod. 
 * Nightly full renders to fix holes

It seems that these happen near the edge of where a player has loaded the world by being there. The chunks will show up in world.pending, but then wont ever get processed? Reloading the mod then clears them from this list and they are never handled until a new full render takes place. 

I have a reproducing setup and I am happy to help provide any further details. In the mean time I will attempt to use the Dynmap-2.2-alpha-1-forge-1.7.10.jar  file in your provided link to see if this somehow is different then the HEAD version I have.

**Comment by jmurrayufo** [comment] 2015-04-06 15:30
Seems to be fixed in Dynmap-2.2-alpha-2-forge-1.7.10.jar.

**Closed** 2015-05-10 14:16 UTC
Labels: Bug, Fixed
